name: Tag Releases

on:
  push:
    branches:
      - "main"
    paths:
      - "version.txt"

  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push tag
        run: |
          VERSION="$(cat version.txt)"
          git tag "$VERSION"
          git push origin tag "$VERSION"