name: Tag Releases

on:
  push:
    branches:
      - "main"
    paths:
      - "version.txt"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          VERSION="$(cat version.txt)"
          git tag "$VERSION"
          git push origin tag "$VERSION"